Add indexing env vars
redhat-performance/web-burner pull request #35
Opened 2022-04-28 11:13 UTC by rsevilla87

Add indexing related env vars in order to make ES indexing more configurable from the command line

Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

2022-04-28 19:17 UTC, mukrishn approved these changes

2022-04-28 20:15 UTC, smalleni requested changes
Seems like there was an accidental replacement of defaultIndex with esServers?

2022-04-28 20:15 UTC, smalleni commented on workload/cfg_delete_icni1_f5_cluster_density.yml
> +    esServers: {{ .ES_INDEX }}
Shouldn't this be defaultIndex

2022-04-28 20:15 UTC, smalleni commented on workload/cfg_delete_icni1_f5_node_density.yml
> +    esServers: {{ .ES_INDEX }}
defaultIndex

2022-04-28 20:15 UTC, smalleni commented on workload/cfg_delete_icni2_cluster_density2.yml
> +    esServers: {{ .ES_INDEX }}
defaultIndex

2022-04-28 20:16 UTC, smalleni commented on create_icni2_workload.sh
> +export ES_SERVER=${ES_INDEX:-https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com}
Also ES_SERVER

2022-04-29 10:30 UTC, rsevilla87 commented
> Seems like there was an accidental replacement of defaultIndex with esServers?

Fixed, thanks for noticing it

2023-03-01 12:18 UTC, merged